learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views



app_name = 'basic_app'


urlpatterns = [

    path('register/', views.register, name='register')


]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))

]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.




class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)


    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm




# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')



def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'basic_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


# Create your views here.

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
  <nav class = 'navbar navbar-default navbar-static-top'>
    <div class="container">
      <ul class="nav navbar-nav">
        <li><a class ="navbar-brand" href="{%url 'index'%}">DJANGO</a></li>
        <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
        <li><a href="{% url 'basic_app:register' %}" class="navbar-link">Register</a></li>

      </ul>

    </div>

  </nav>
  <div class="container">

    {% block body_block %}
    {% endblock %}


  </div>


</body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five</h1>

</div>


{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}

{% load static %}


{% block body_block %}

<div class="jumbotron">

  {% if registered %}
    <h1>Thank you for registering</h1>
  {%else%}
  <h1>Register Here!</h1>
  <h3>Fill out Form:</h3>


  <form enctype="multipart/form-data" method="POST">
    {% csrf_token%}
    {{user_form.as_p}}
    {{profile_form.as_p}}
    <input type="submit" name="" value="Register">






  </form>
  {% endif %}


</div>


{% endblock%}